[linters]
enable-all = true
disable = [
    "gci", # conflicts with gofumpt
    "golint", # deprecated
    "interfacer", # deprecated
    "maligned", # deprecated
    "scopelint", # deprecated
    "exhaustivestruct",
    "dupl",
  ]
